### ISSUE TITLE
Best approach for responsive images?

### ISSUE THREAD

**Issue by tom-parker** [Financial-Times/n-image#1]
# Information

There are a few different apporaches we can take when implementing this and there are a few different scenarios we need to cover. 

We need to -
1. Load appropriate image for the screen dimensions e.g. on article pages
2. Only load images when they are required. Currently some images on streams are not shown at mobile breakpoints but are on larger breakpoints. This means we need the abilty to only request images at certain breakpoints.

The first scenario is fairly easy to cover with a couple of caveats. The code below or similar is recommended by the [responsive image community group](https://responsiveimages.org/)

```html
	<picture class="article-image-object">
		<!--[if IE 9]><video style="display: none;"><![endif]-->
		<source srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=750%C3%97350&w=750&h=350" media="(min-width: 640px)">
		<source srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150"/>
		<!--[if IE 9]></video><![endif]-->

		<img srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150" alt="Some alt text"/>
	</picture>
```

The main issue with this approach is when there is no picture support and no JS, all that gets shown is the alt text for the fallback image. Another approach is to use a `src` attribute on the fallback image instead

```html
	<picture class="article-image-object">
		<!--[if IE 9]><video style="display: none;"><![endif]-->
		<source srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=750%C3%97350&w=750&h=350" media="(min-width: 640px)">
		<source srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150"/>
		<!--[if IE 9]></video><![endif]-->

		<img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150" alt="Some alt text"/>
	</picture>
``` 
"Unfortunately, adding a src attribute with an external source to the img element in your picture element isn't a good workaround either, as any browser that exists today will fetch that src url even if it is not going to be used" - http://scottjehl.github.io/picturefill/#support

To avoid the double download but also show an image when there is no JS we could look at using a no-script fallback. This approach might also involve some CSS work as by default you'd see the alt text from the fallback in addition to the no-script image.

```html
	<picture class="article-image-object">
		<!--[if IE 9]><video style="display: none;"><![endif]-->
		<source srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=750%C3%97350&w=750&h=350" media="(min-width: 640px)">
		<source srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150"/>
		<!--[if IE 9]></video><![endif]-->

		<img srcset="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150" alt="Some alt text"/>

		<noscript>
			<img src="https://placeholdit.imgix.net/~text?txtsize=33&txt=350%C3%97150&w=350&h=150" alt="Some alt text"/>
		</noscript>
	</picture>
```

Again this isn't a recommended solution to the issue - https://github.com/scottjehl/picturefill/issues/499

Some results for different approaches. This will need more testing as there will be subtleties in browsers that support srcset but not picture etc.

|                                 | No img src for fallback              | Img src for fallback                       | Img srcset for fallback              | Img srcset for fallback + no-script  |
|---------------------------------|--------------------------------------|--------------------------------------------|--------------------------------------|--------------------------------------|
| No picture support / No JS      | Alt text only                        | Fallback img shown                         | Alt text only                        | No-script fallback shown             |
| No picture support / JS         | Relevant image shown after JS loaded | Double request when JS is loaded           | Relevant image shown after JS loaded | Relevant image shown after JS loaded |
| Picture support (JS not needed) | Relevant image shown                 | Relevant image shown                       | Relevant image shown                 | Relevant image shown                 |

# Proposal

From the information I've read, it seems the standard solution is to remove the `src` attribute on the fallback image for non essential images (e.g where not shown on mobile). For images that must be shown, a `src` attribute must be used and a double download will occur on non-supporting browsers. As mentioned in [this issue](https://github.com/scottjehl/picturefill/issues/499) there is currently no nice way of covering all the bases. Some compromise will have to happen somewhere.

**Comment by wheresrhys** [comment]
What are you thinking for the syntax that devs would need to write in their templates? Handlebars helper or a partial with variables passed in?

**Comment by tom-parker** [comment]
@wheresrhys I hadn't yet. Any preference?

**Comment by wheresrhys** [comment]
Very, very mild preference for a helper, though the extra complication involved in storing the helper in this component but making it available server side probably isn't worth it

**Comment by commuterjoy** [comment]
all done?

**Comment by tom-parker** [comment]
Yep, just getting some stats from the homepage before shipping it.
