### ISSUE TITLE
Supply the image URLs from outside?

### ISSUE THREAD

**Issue by charypar** [Financial-Times/n-image#4]
This is more of an open question than an issue, but would it be a bit cleaner if the API didn't internally rely on `next-express-setup` (well `next-handlebars` really) and its `resize` helper?

This would let people do things like use existing static image sources rather than going through geebee (for whatever reason) and remove an implicit dependency on next, n-image doesn't necessarily have to have, making it potentially a bit more widely useful.

**Comment by tom-parker** [comment]
Yep, this definitely needs to get done. The implementation at the moment makes it very very simple but as you said you're tied into geebee. I know there also discussion about needing to pass extra params to geebee such as tint which the current implementation won't allow.
